var pokemons = [{
		num: '001',
		name: 'Bulbasaur',
		img: 'http://www.serebii.net/pokemongo/pokemon/001.png',
		type: ['Grass', 'Poison'],
		height: '0.71 m',
		weight: '6.9 kg',
		candy: 'Bulbasaur Candy',
		candy_count: 25,
		egg: '2 km',
		age: '99 age',
		spawn_chance: 0.69,
		avg_spawns: 69,
		spawn_time: '20:00',
		multipliers: [1.58],
		weaknesses: ['Fire', 'Ice', 'Flying', 'Psychic'],
		next_evolution: [{
				num: '000',
				name: 'Ivysaur',
			},
			{
				num: '002',
				name: 'Venusaur',
			},
		],
	},
	{
		num: '002',
		name: 'Ivysaur',
		img: 'http://www.serebii.net/pokemongo/pokemon/002.png',
		type: ['Grass', 'Poison'],
		height: '0.99 m',
		weight: '13.0 kg',
		candy: 'Bulbasaur Candy',
		candy_count: 100,
		egg: 'Not in Eggs',
		spawn_chance: 0.042,
		avg_spawns: 4.2,
		age: '99 age',
		spawn_time: '07:00',
		multipliers: [1.2, 1.6],
		weaknesses: ['Fire', 'Ice', 'Flying', 'Psychic'],
		next_evolution: [{
				num: '003',
				name: 'Bulbasaur',
			},
			{
				num: '001',
				name: 'Venusaur',
			}
		],
	},
	{
		num: '003',
		name: 'Venusaur',
		img: 'http://www.serebii.net/pokemongo/pokemon/003.png',
		type: ['Grass', 'Poison'],
		height: '2.01 m',
		weight: '100.0 kg',
		candy: 'Bulbasaur Candy',
		age: '99 age',
		egg: 'Not in Eggs',
		spawn_chance: 0.017,
		avg_spawns: 1.7,
		spawn_time: '11:30',
		multipliers: null,
		weaknesses: ['Fire', 'Ice', 'Flying', 'Psychic'],
		next_evolution: [{
				num: '004',
				name: 'Bulbasaur',
			},
			{
				num: '002',
				name: 'Ivysaur',
			},
		],
	},
	{
		num: '004',
		name: 'Charmander',
		img: 'http://www.serebii.net/pokemongo/pokemon/004.png',
		type: ['Fire'],
		height: '0.61 m',
		weight: '8.5 kg',
		candy: 'Charmander Candy',
		candy_count: 25,
		egg: '2 km',
		spawn_chance: 0.253,
		avg_spawns: 25.3,
		spawn_time: '08:45',
		age: '99 age',
		multipliers: [1.65],
		weaknesses: ['Water', 'Ground', 'Rock'],
		next_evolution: [{
				num: '005',
				name: 'Charmeleon',
			},
			{
				num: '003',
				name: 'Charizard',
			},
		],
	},
	{
		num: '005',
		name: 'Charmeleon',
		img: 'http://www.serebii.net/pokemongo/pokemon/005.png',
		type: ['Fire'],
		height: '1.09 m',
		weight: '19.0 kg',
		candy: 'Charmander Candy',
		candy_count: 100,
		egg: 'Not in Eggs',
		spawn_chance: 0.012,
		age: '99 age',
		avg_spawns: 1.2,
		spawn_time: '19:00',
		multipliers: [1.79],
		weaknesses: ['Water', 'Ground', 'Rock'],
		next_evolution: [{
				num: '006',
				name: 'Charmander',
			},
			{
				num: '004',
				name: 'Charizard',
			},
		],
	},
	{
		num: '006',
		name: 'Charizard',
		img: 'http://www.serebii.net/pokemongo/pokemon/006.png',
		type: ['Fire', 'Flying'],
		height: '1.70 m',
		weight: '90.5 kg',
		candy: 'Charmander Candy',
		egg: 'Not in Eggs',
		spawn_chance: 0.0031,
		avg_spawns: 0.31,
		spawn_time: '13:34',
		multipliers: null,
		age: '99 age',
		weaknesses: ['Water', 'Electric', 'Rock'],
		next_evolution: [{
				num: '007',
				name: 'Charmander',
			},
			{
				num: '005',
				name: 'Charmeleon',
			},
		],
	},
	{
		num: '007',
		name: 'Squirtle',
		img: 'http://www.serebii.net/pokemongo/pokemon/007.png',
		type: ['Water'],
		height: '0.51 m',
		weight: '9.0 kg',
		candy: 'Squirtle Candy',
		candy_count: 25,
		egg: '2 km',
		spawn_chance: 0.58,
		age: '99 age',
		avg_spawns: 58,
		spawn_time: '04:25',
		multipliers: [2.1],
		weaknesses: ['Electric', 'Grass'],
		next_evolution: [{
				num: '008',
				name: 'Wartortle',
			},
			{
				num: '006',
				name: 'Blastoise',
			},
		],
	},
	{
		num: '007',
		name: 'Squirtle',
		img: 'http://www.serebii.net/pokemongo/pokemon/007.png',
		type: ['Water'],
		height: '0.51 m',
		weight: '9.0 kg',
		candy: 'Squirtle Candy',
		candy_count: 25,
		egg: '2 km',
		spawn_chance: 0.58,
		age: '99 age',
		avg_spawns: 58,
		spawn_time: '04:25',
		multipliers: [2.1],
		weaknesses: ['Electric', 'Grass'],
		next_evolution: [{
				num: '008',
				name: 'Wartortle',
			},
			{
				num: '006',
				name: 'Blastoise',
			},
		],
	},
]